# Generated by Django 5.0.6 on 2024-06-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_usercontext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
