# Generated by Django 5.0.6 on 2024-06-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_usercontext_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontext",
            name="context_data",
            field=models.JSONField(default=None, null=True),
        ),
    ]
