# Generated by Django 4.2.13 on 2024-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_usercontext_context_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="level"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="topic"),
        ),
    ]
