# Generated by Django 4.2.13 on 2024-06-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_level_image_alter_topic_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/level/"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/topic/"),
        ),
    ]
