# Generated by Django 4.2.13 on 2024-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_level_image_alter_topic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="nivel",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="level",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
