# Generated by Django 4.2.13 on 2024-06-26 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_level_nivel_alter_level_image_alter_topic_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskills",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.level"
            ),
        ),
        migrations.AlterField(
            model_name="userskills",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.topic"
            ),
        ),
    ]
